# ==================
# Project Details
# ==================
name: "linkedin"
config-version: 2
require-dbt-version:
- ">=1.3.0"
- "<2.0.0"
version: "0.8.0"

# ==================
# File Path Configs
# ==================
model-paths:
- "models"
- "prophecy-sources"

# ==================
# Variable Configs
# ==================
vars:
  linkedin:
    account_history: "{{ ref('stg_linkedin_ads__account_history') }}"
    ad_analytics_by_campaign: "{{ ref('stg_linkedin_ads__ad_analytics_by_campaign')\
      \ }}"
    ad_analytics_by_creative: "{{ ref('stg_linkedin_ads__ad_analytics_by_creative')\
      \ }}"
    campaign_group_history: "{{ ref('stg_linkedin_ads__campaign_group_history') }}"
    campaign_history: "{{ ref('stg_linkedin_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_linkedin_ads__creative_history') }}"
  linkedin_ads__campaign_passthrough_metrics: []
  linkedin_ads__creative_passthrough_metrics: []

# ==================
# Model Configs
# ==================
models:
  linkedin:
    "+materialized": "table"
    "+schema": "linkedin_ads"
